name: ChatPronouns
version: ${project.version}
main: xyz.fluxinc.chatpronouns.ChatPronouns
api-version: 1.13
description: Shows a players pronouns in chat, if they have them set
depends: FluxCore
authors: [CelesteMagisteel]
commands:
  removepronouns:
    usage: /removepronouns [player]
permissions:
  chatpronouns.custom:
    default: op
  chatpronouns.others:
    default: op
